### ISSUE TITLE
Create todo page

### ISSUE THREAD

**Issue by mulearn-mac** [mulearn-mac/mulearn-mac-campus-chapter-website#8]
## Create a todo list page for planning future campus activities

- [ ] Create a todo list page.
- [ ] Create related files.
- [ ] Connect with firebase firestore and firestore library.
- [ ] Connect with firestore script (local methods).
